/**
 * Social → command signals bridge.
 *
 * Voice and social deploy as independent Vercel projects (no workspace dep
 * between them), so this file does NOT import from `apps/social`. Instead it
 * reads the social tool's tables (`public.*`) directly via voice's pg pool
 * and ports the detector pattern from `apps/social/lib/action-engine.ts`.
 *
 * Anytime a new detector ships in social, mirror it here. Both files live in
 * the same monorepo and the test suite in social keeps the canonical
 * detector logic honest.
 */
import 'server-only';
import { q } from '../../db';
import type { SignalDraft } from './detectors';

// ─── Inline port of the social types we need (snake_case mirrors DB) ───────

type PostStatus = 'planned' | 'captured' | 'edited' | 'approved' | 'ready' | 'scheduled' | 'posted';

interface SocialClient {
  id: string;
  name: string;
  slug: string;
  archived: boolean;
}

interface SocialMonth {
  id: string;
  client_id: string;
  month: string;
}

interface SocialPost {
  id: string;
  month_id: string;
  post_date: string;
  status: PostStatus;
  shoot_id: string | null;
  description: string | null;
  owner_person_id: string | null;
  asset_url: string | null;
  content_type: string;
  platform: string | null;
}

interface SocialShoot {
  id: string;
  month_id: string;
  bundle_number: number;
  scheduled_date: string | null;
  scheduled_time: string | null;
  location: string | null;
  assigned_to: string | null;
  assigned_person_id: string | null;
}

interface SocialFrame {
  client_id: string;
  min_lead_time_days: number | null;
}

// ─── Snapshot loader ──────────────────────────────────────────────────────

interface SocialSnapshot {
  today: Date;
  clients: SocialClient[];
  months: SocialMonth[];
  posts: SocialPost[];
  shoots: SocialShoot[];
  frames: SocialFrame[];
}

async function loadSnapshot(today: Date): Promise<SocialSnapshot> {
  // The social tool's tables live in the public schema and are readable from
  // any app on the same Postgres cluster. Each query degrades gracefully —
  // if a table is missing (e.g., on a fresh dev DB without migrations 0001-
  // 0010 applied), we treat it as empty and return zero signals.
  const safe = async <T>(sql: string): Promise<T[]> => {
    try {
      const rows = await q(sql);
      return rows as unknown as T[];
    } catch {
      return [];
    }
  };
  const [clients, months, posts, shoots, frames] = await Promise.all([
    safe<SocialClient>(
      `select id, name, slug, archived from public.clients where archived = false`
    ),
    safe<SocialMonth>(`select id, client_id, month::text as month from public.months`),
    safe<SocialPost>(
      `select id, month_id, post_date::text as post_date, status::text as status,
              shoot_id, description, owner_person_id, asset_url, content_type::text as content_type, platform
         from public.posts`
    ),
    safe<SocialShoot>(
      `select id, month_id, bundle_number, scheduled_date::text as scheduled_date,
              scheduled_time, location, assigned_to, assigned_person_id
         from public.shoots`
    ),
    safe<SocialFrame>(
      `select client_id, min_lead_time_days from public.strategic_frames`
    ),
  ]);
  return { today, clients, months, posts, shoots, frames };
}

// ─── Detector ports ────────────────────────────────────────────────────────
// These mirror a subset of apps/social/lib/action-engine.ts. We only port
// the detectors whose output maps to a command.tasks creation rule. The full
// notification feed continues to be generated by the social app's own cron.

const DAY_MS = 86_400_000;

function startOfWeekSunday(d: Date): Date {
  const x = new Date(d);
  x.setHours(0, 0, 0, 0);
  x.setDate(x.getDate() - x.getDay()); // back to Sunday
  return x;
}
function endOfWeekSunday(d: Date): Date {
  const start = startOfWeekSunday(d);
  return new Date(start.getTime() + 7 * DAY_MS - 1);
}
function parseISODate(s: string): Date {
  return new Date(s);
}
function differenceInCalendarDays(a: Date, b: Date): number {
  const da = new Date(a.getFullYear(), a.getMonth(), a.getDate()).getTime();
  const db = new Date(b.getFullYear(), b.getMonth(), b.getDate()).getTime();
  return Math.round((da - db) / DAY_MS);
}

/** Stuck post — planned, due this week, has a shoot. Mirror of social. */
function stuckPosts(s: SocialSnapshot): SignalDraft[] {
  const out: SignalDraft[] = [];
  const start = startOfWeekSunday(s.today);
  const end = endOfWeekSunday(s.today);
  const monthById = new Map(s.months.map(m => [m.id, m]));
  const clientById = new Map(s.clients.map(c => [c.id, c]));
  for (const p of s.posts) {
    if (p.status !== 'planned') continue;
    if (!p.shoot_id) continue;
    const d = parseISODate(p.post_date);
    if (d < start || d > end) continue;
    const month = monthById.get(p.month_id);
    const client = month ? clientById.get(month.client_id) : null;
    out.push({
      source: 'social',
      kind: 'social.stuck_post',
      dedup_key: `social.stuck_post:stuck_post:${p.id}`,
      artifact_kind: 'post',
      artifact_id: p.id,
      payload: {
        post_id: p.id,
        post_date: p.post_date,
        owner_person_id: p.owner_person_id,
        client_id: client?.id ?? null,
        client_slug: client?.slug ?? null,
        client_name: client?.name ?? null,
        month_id: p.month_id,
        shoot_id: p.shoot_id,
        description: p.description,
        platform: p.platform,
        content_type: p.content_type,
      },
    });
  }
  return out;
}

/** Shoot unassigned — scheduled in next 7 days, no person assigned. */
function shootUnassigned(s: SocialSnapshot): SignalDraft[] {
  const out: SignalDraft[] = [];
  const horizon = new Date(s.today.getTime() + 7 * DAY_MS);
  const monthById = new Map(s.months.map(m => [m.id, m]));
  const clientById = new Map(s.clients.map(c => [c.id, c]));
  for (const sh of s.shoots) {
    if (!sh.scheduled_date) continue;
    if (sh.assigned_person_id) continue;
    if (sh.assigned_to && sh.assigned_to.trim()) continue;
    const d = parseISODate(sh.scheduled_date);
    if (d < s.today || d > horizon) continue;
    const month = monthById.get(sh.month_id);
    const client = month ? clientById.get(month.client_id) : null;
    out.push({
      source: 'social',
      kind: 'social.shoot_unassigned',
      dedup_key: `social.shoot_unassigned:unassigned:${sh.id}`,
      artifact_kind: 'shoot',
      artifact_id: sh.id,
      payload: {
        shoot_id: sh.id,
        bundle_number: sh.bundle_number,
        scheduled_date: sh.scheduled_date,
        scheduled_time: sh.scheduled_time,
        location: sh.location,
        client_id: client?.id ?? null,
        client_slug: client?.slug ?? null,
        client_name: client?.name ?? null,
        month_id: sh.month_id,
      },
    });
  }
  return out;
}

/** Asset overdue — captured but no asset URL, going live within 5 days. */
function assetOverdue(s: SocialSnapshot): SignalDraft[] {
  const out: SignalDraft[] = [];
  const monthById = new Map(s.months.map(m => [m.id, m]));
  const clientById = new Map(s.clients.map(c => [c.id, c]));
  for (const p of s.posts) {
    if (p.status !== 'captured') continue;
    if (p.asset_url && p.asset_url.trim()) continue;
    const d = parseISODate(p.post_date);
    const days = differenceInCalendarDays(d, s.today);
    if (days < 0 || days > 5) continue;
    const month = monthById.get(p.month_id);
    const client = month ? clientById.get(month.client_id) : null;
    out.push({
      source: 'social',
      kind: 'social.asset_overdue',
      dedup_key: `social.asset_overdue:asset_overdue:${p.id}`,
      artifact_kind: 'post',
      artifact_id: p.id,
      payload: {
        post_id: p.id,
        post_date: p.post_date,
        owner_person_id: p.owner_person_id,
        client_id: client?.id ?? null,
        client_slug: client?.slug ?? null,
        client_name: client?.name ?? null,
        month_id: p.month_id,
        days_to_live: days,
      },
    });
  }
  return out;
}

/** Lead-time-tight — earliest post on a shoot is inside the lead window. */
function leadTimeTight(s: SocialSnapshot): SignalDraft[] {
  const out: SignalDraft[] = [];
  const monthById = new Map(s.months.map(m => [m.id, m]));
  const clientById = new Map(s.clients.map(c => [c.id, c]));
  const frameByClient = new Map(s.frames.map(f => [f.client_id, f]));
  for (const sh of s.shoots) {
    if (!sh.scheduled_date) continue;
    const month = monthById.get(sh.month_id);
    if (!month) continue;
    const frame = frameByClient.get(month.client_id);
    const minLead = frame?.min_lead_time_days ?? 5;
    const linked = s.posts.filter(p => p.shoot_id === sh.id);
    if (linked.length === 0) continue;
    const earliest = linked
      .map(p => parseISODate(p.post_date))
      .reduce((a, b) => (a < b ? a : b));
    const days = differenceInCalendarDays(earliest, parseISODate(sh.scheduled_date));
    if (days >= minLead) continue;
    const client = clientById.get(month.client_id);
    out.push({
      source: 'social',
      kind: 'social.lead_time_tight',
      dedup_key: `social.lead_time_tight:lead_time:${sh.id}`,
      artifact_kind: 'shoot',
      artifact_id: sh.id,
      payload: {
        shoot_id: sh.id,
        bundle_number: sh.bundle_number,
        scheduled_date: sh.scheduled_date,
        days_between: days,
        min_lead_required: minLead,
        client_id: client?.id ?? null,
        client_slug: client?.slug ?? null,
        client_name: client?.name ?? null,
        month_id: sh.month_id,
        assigned_person_id: sh.assigned_person_id,
      },
    });
  }
  return out;
}

// ─── Public surface ────────────────────────────────────────────────────────

/**
 * Read social state, run the social-side detectors, return signal drafts.
 * Failure-tolerant — any unexpected error returns an empty array so the
 * agency-wide ingest cron never wedges on a single source app.
 */
export async function harvestSocialSignals(today: Date = new Date()): Promise<SignalDraft[]> {
  try {
    const snapshot = await loadSnapshot(today);
    return [
      ...stuckPosts(snapshot),
      ...shootUnassigned(snapshot),
      ...assetOverdue(snapshot),
      ...leadTimeTight(snapshot),
    ];
  } catch {
    return [];
  }
}
